stages:
  load_data:
    cmd: python src/utils/data_utils.py --config=params.yaml
    deps:
      - src/utils/utils.py
      - src/utils/data_utils.py
      - data_given/winequality.csv
    outs:
      - data/raw/winequality.csv
  split_data:
    cmd: python src/utils/data_utils.py --config=params.yaml --stage=split_and_save_data
    deps:
      - data/raw/winequality.csv
    outs:
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv

  train_and_evaluate:
    cmd: python src/utils/data_utils.py --config=params.yaml --stage=train_and_evaluate
    deps:
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    metrics:
      - report/scores.json:
          cache: false
      - report/params.json:
          cache: false
    outs:
      - saved_models/model.joblib
